on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly-2021-03-23
          - nightly-2021-05-24
          - nightly-2021-07-25
          - nightly-2021-09-26
          - nightly-2021-11-27
          - nightly-2022-01-28
          - nightly-2022-02-29
          - nightly-2022-03-30
    name: Rust ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
