on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly-2020-04-09
          - nightly-2021-04-10
          - nightly-2021-05-10
          - nightly-2021-06-10
          - nightly-2021-07-10
          - nightly-2021-08-10
          - nightly-2021-09-10
          - nightly-2021-10-10
          - nightly-2021-11-10
          - nightly-2021-12-10
          - nightly-2022-04-11
    name: Rust ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
