on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.42.0
          - 1.48.0
          - 1.52.0
          - 1.54.0
          - 1.56.0
          - nightly
    name: Rust ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
