on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly-2022-03-05
          - nightly-2022-03-06
          - nightly-2022-03-07
          - nightly-2022-03-08
          - nightly-2022-03-09
          - nightly-2022-03-10
          - nightly-2022-03-11
    name: Rust ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
